spring:
  application:
    name: inventory
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

server:
  port: 8080

logging:
  file:
    name: logs/api-local.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    diy.user: debug

