spring:
  application:
    name: inventory
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/msa
#    username: backend
#    password: backend
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 9090

logging:
  file:
    name: logs/api-local.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    diy.user: debug